build:
  name: devops-java-app
  jarName: devops-java-app-0.0.1-SNAPSHOT.jar

deployment:
  - appName: devops-java-app
    environments:
      - env: local-dev
        branch: develop
        deployFlag: enable
        container: enable
        spaceName: dev-namespace
      - env: production
        branch: main
        deployFlag: disable
        spaceName: prod-namespace